apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
selector:
    app: petclinic
  type: LoadBalancer
  
 